### ISSUE TITLE
Show Custom Post Types in REST

### ISSUE THREAD

**Issue by nicschumann** [work-shop/medmates#1]
*For the Calendar*

We should expose our custom post types to the Wordpress REST API, so that we can easily get JSON views of our data. This will enable us to utilize a front-end-only library to render features like the calendar, without having to do any processing on the back-end. What we'll end up doing is pulling a list of events off of the API on the client side, passing them to a plugin that we choose, and then using the plugin to generate the calendar, which we'll be able to style and assign custom events to.

Exposing custom post types to REST is pretty easy; there's a boolean option for the `register_post_type` function, `show_in_rest`, which just needs to be set to true. [More info on the codex page](https://codex.wordpress.org/Function_Reference/register_post_type#show_in_rest).

There's good info about pagination and data embedding and the general design of the Wordpress REST API at [the codex page for that](https://developer.wordpress.org/rest-api/), which is worth a browse.

**Comment by teddybradford** [comment]
92b57053ebf7301e17385c53a69d1b32f0cd2eae
